%YAML 1.2
---
site:
  name: "Accodeing"
  domains:
  - "accodeing.com"
  - "accodeing.dev"
  content_root: "content"

build:
- name: "CSON -> JSON"
  script: "plugins/cson_to_json.nims"
  config:
    glob: "content/**/*.cson"
- name: "JSON loader"
  script: "plugins/json_loader.nims"
  after: "CSON -> JSON"
  config:
    context_path_prefix: "pages"
    glob: "content/**/*.json"
- name: "JSON serialiser"
  script: "plugins/json_serialiser.nims"
  after: "Markdown"
  config:
    context_path_contains_segment: "*"
- name: "Nunjucks"
  script: "plugins/nunjucks_deno.nims"
  after: "JSON serialiser"
# - name: "Transfigure"
#   script: "plugins/img_resize.nims"
#   after:
#   - "Picturesque"
#   before:
#   - "Parcel"
#   config:
#     svg-fallback: true
# - name: "Picturesque"
#   script: "plugins/picturesque.nims"
#   after:
#   - "Nunjucks"
#   config:
#     include: "*.gif, *.jpg, *.jpeg, *.png, *.webp, *.svg"
- name: "Markdown"
  script: "plugins/markdown.nims"
  after:
  - "JSON loader"
  config:
    content_starts_with: "[//]:"
    # context_path_contains_segment: ".?-markdown."
    # context_path_contains_string: "-markdown"
# - name: "Parcel"
#   script: "plugins/parcel.nims"
#   config:
#     svg-fallback: true
